### ISSUE TITLE
single-account-ecs module no longer lists AWS provider as required

### ISSUE THREAD

**Issue by if-jeremy** [sysdiglabs/terraform-aws-secure-for-cloud#113]
It would appear that with commit a20400ed6ce7b9a94204687211a9fd34d5cdde59 in May, the AWS provider is no longer listed as required in examples/single-account-ecs/versions.tf.  While I'm sure for many this will still work (because they probably only have one AWS provider), we actually deploy Sysdig into two accounts, which means we have 2 AWS providers.  Without the AWS provider requirement listed, specifying the correct provider for the module results in a warning from "terraform plan":

Warning: Provider aws is undefined

   on sysdig-secure.tf line 18, in module "secure-for-cloud-backups":
   18:         aws = aws.account2

 Module module.secure-for-cloud-account2 does not declare a provider named aws.
 If you wish to specify a provider configuration for the module, add an entry
 for aws in the required_providers block within the module.

**Comment by wideawakening** [comment]
hey @if-jeremy,

we removed those providers because [tf linter was warning us that aws resources were not used in the example themselves ](https://github.com/terraform-linters/tflint/blob/v0.36.2/docs/rules/terraform_unused_required_providers.md) (in our case only in child modules).

i thought that maybe your error could be bypassed defining the `required_providers` in the caller code, but seems like its required in the children module indeed - will restore them in a PR.
